; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
monitor_speed = 115200
framework = arduino
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	beegee-tokyo/DHT sensor library for ESPx@^1.19
	fscii/OpenFontRender@^1.0.0
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit BME280 Library@^2.3.0
	claws/BH1750@^1.3.0
	knolleary/PubSubClient@^2.8
    